### PR TITLE
Finish Login Integration (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by shkfnly**
I've integrated Facebook and Google login, but had to semi eject the application. Working on uport currently but there is a weird bug showing up.

### CODE REVIEW

**Comment by edzillion** [comment]
hey ashoka, the plan for the MVP is not to support google / fb / uport logins. we are just using amazon for auth for the moment.

i'll take this over as it is part of the SMS validation & the API security stuff too

**Comment by shkfnly** [comment]
The google and facebook are already done, so we just would need to create users from the logins.

**Comment by shkfnly** [comment]
Where is the MVP scope defined, and how does it relate to the wireframes

**Comment by edzillion** [comment]
it's a WIP 

https://docs.google.com/document/d/1x__7blpl8u-J7RdThxLO77StFP95WvwPqm3cwjXfDLc/edit?ts=5b646308#heading=h.czfgjzs0ttvh

we could do with your help firming it up. there is another doc floating around

**Comment by shkfnly** [comment]
Finished All Logins, Will help write logic to make sure these can all work together. This can now be in Scope for the MVP....because it's already done :)

**Comment by edzillion** [comment]
Got this branch up and working and I realised that out current validation strategy requires some kind of feature to add new users.

This can be achieved on the console (unworkably clunky) or through the AWS SDK. I'm putting together a v basic ionic app to test this flow and the repo is here:

https://github.com/CirclesUBI/circles-admin

**Pull request closed without merging**
